services:
  hr-app:
    build: .
    container_name: hr-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./db:/app/db
      - ./templates:/app/templates
      - ./generated:/app/generated
